### ISSUE TITLE
RIPMotion direction classification is incorrect

### ISSUE THREAD

**Issue by deprecatedcoder** [locomotionvault/locomotionvault#4]
I'm not sure if it's better classified as "Walking" or "Device", but it is explicitly _not_ "Gaze". 

Hating gaze-based was actually the impetus for it.

Using the two controllers at the hips was also what would be considered an experimental hack, whereas the first version with the controller in the belt is more akin to the actual intent, which is to have the hip direction tracked by a device (or external camera).  Either way, hip direction is really the core of it.

Just figured I would toss it out there.  This is a really cool aggregation of all of these options and kind of makes me want to dust things off again and pick up where it was left off.

**Comment by locomotionvault** [comment]
Great, thanks for letting us know. You are right. I agree "Walking" would be a more appropriate categorization for it.
Would you like to send me a pull request with the updated value for the "direction" attribute so that I can merge it? That way you'll get the credit for contributing to the project. I can also update it on our end if you prefer that.

**Comment by maxdiluca** [comment]
Hi Ryan, thanks. You are right. Maybe "device" captures both implementations
